sudo: required

branches:
  except:
    - template

env:
  global:
    - TRAVIS_USER_UID=$(id -u)
    - secure: byIArJzJWVph6ZSNAhNJUpxzfhnhAO5JO0unJjlNTqFyNhMC8VSsOTdeP7JlWKld1edGn3AJ4vtmYzjNh4ci1JpAXyWqYKE8XM3G8mKQq1bXEVFOsrOJ/gppRICQFJ/d24ui4E2y/BgDRNnzktmLUFdoOa9IHZnmVhqbMg9l660fdFhU0AkWVMYzPd9mzIf0g5oSbUliYw/ESI3E3hC95eGe4pZRIJ+SL18NPOo+jbaoNY/ly/WjgvNWkEtbllkPu8YvTysDkZr3OteIjIAqs1zbgD2zsNEgKhnwyPD1FRXp3Unql5AgrHuy6vxmkVgjqUzEHqojCqLDMnT+lYBAPIHsRnWOeCBIIFWaMWv8vKShm3VIi0bBMLMY4tZ+4kXtgCvf20Kw6fiIpFOlsdtoIN0DFfmw3gIdfJ1SdXhkO7jpS0SXMFiwK5r5plMaqxla0XfR1iSXLRDO5X778Ua5BFJ/0ppb5SmNuELlcJzy5lITnAaztazp3RwE6y0cjs+A+QSCdqVAs6F/8fAdGXhHez0Zkp0tKbDkW3KyFEDPKqN0ye1kKNnHNG3hbN/cTap4ZSBt7TcMcVAeBYAthZwk6annGGxgNxUxVJu5/c7tw6H3Mr9mwXH4XXGVhNbTeqP9cu/uhKBbqjMA09JovYG7U8u6dcNwqwRTyNQ7M/ihRyc=

before_install:
  - openssl aes-256-cbc -K $encrypted_4378f99a3eaa_key -iv $encrypted_4378f99a3eaa_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d

install:
  - sudo apt-get install sshfs
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine

script:
  - sudo .travis/buildrepo
