#!/usr/bin/bash

build() {
    local mod
    local symlink

    # device mapper modules
    for mod in dm-mod dm-snapshot dm-mirror dm-cache dm-cache-smq dm-thin-pool; do
        add_module "$mod"
    done

    # binaries from lvm2
    add_binary "lvm"

    # binaries from device-mapper
    add_binary "dmsetup"

    # from thin-provisioning-tools
    add_binary "pdata_tools"
    for symlink in cache_{check,dump,metadata_size,repair,restore} thin_{check,delta,dump,ls,metadata_size,repair,restore,rmap,trim}; do
        add_symlink "/usr/bin/${symlink}" "pdata_tools"
    done

    # udev rules and lvm configuration
    add_file "/etc/lvm/lvm.conf"

    add_runscript
}

help() {
  cat <<HELPEOF
This hook enables LVM2 volumes in initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
