#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

APK_TOOLS_URI='https://repository.fit.cvut.cz/mirrors/alpine/v3.6/main/x86_64/apk-tools-static-2.7.2-r0.apk'
APK_TOOLS_SHA256='c3a7d903501f6613df703e714426f1d5c3d2e083e38f413180b51a40580e45aa'


echo '\n==> Downloading apk-tools-static'

cd /tmp
wget "$APK_TOOLS_URI"
echo "$APK_TOOLS_SHA256  $(basename "$APK_TOOLS_URI")" | sha256sum -c
tar -xzf $(basename "$APK_TOOLS_URI")


echo '\n==> Installing Alpine Linux'

mkdir -p "$ALPINE_ROOT"/etc/apk
cd "$ALPINE_ROOT"

cp -R "$CLONE_DIR"/.keys etc/apk/keys
cp "$CLONE_DIR"/.travis/repositories etc/apk/repositories
cp /etc/resolv.conf etc/resolv.conf

/tmp/sbin/apk.static \
	--root . --update-cache --initdb --no-progress \
	add alpine-base

mount -t proc none proc
mount --rbind /sys sys
mount --rbind /dev dev
